backend:
  name: github
  repo: jonathanphz/gatsby-netlify-cms-exploration

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: blog-post }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: tumbnail, label: Featured Image, widget: image }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files: 
      - file: src/pages/home/index.md
        label: Home
        name: home
        fields: 
          - { name: path, label: Path }
          - { label: Template Key, name: templateKey, widget: hidden, default: home-page }
          - { label: Title, name: title, widget: string }
          - { label: Hero, name: hero, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - { label: Image and Text Two Column, name: imageTextTwoColumn, widget: object, fields: 
            [ 
              {label: Reverse Layout, name: reverseLayout, widget: boolean, default: false }, 
              {label: Image, name: image, widget: object, fields: [{label: Image Upload, name: imagePath, widget: image}, {label: Image Alt Text, name: imageAlt, widget: string}]},
              {label: Text, name: text, widget: markdown }
            ]
          }
          - { label: Grid Items, name: gridItems, widget: list, fields: 
              [
                { label: Item Image, name: itemImage, widget: image },
                { label: Item Heading, name: itemHeading, widget: text },
                { label: Item Text, name: itemText, widget: text }
              ]
            }
      - file: src/pages/about/index.md
        label: About
        name: about
        fields: 
          - { name: path, label: Path }
          - { label: Template Key, name: templateKey, widget: hidden, default: home-page }
          - { label: Title, name: title, widget: string }
          - { label: Hero, name: hero, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - { label: Image and Text Two Column, name: imageTextTwoColumn, widget: object, fields: 
            [ 
              {label: Reverse Layout, name: reverseLayout, widget: boolean, default: false }, 
              {label: Image, name: image, widget: object, fields: [{label: Image Upload, name: imagePath, widget: image}, {label: Image Alt Text, name: imageAlt, widget: string}]},
              {label: Text, name: text, widget: markdown }
            ]
          }
